server:
  port: 7000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:  #路由数组[路由 就是指定当请求满足什么条件的时候转到哪个微服务]
        - id: product_route
          uri: lb://service-product
          order: 1
          predicates:
            - Path=/product-serv/**
#            - Age= 18,60
          filters:
            - StripPrefix=1
#            - Log=true,true #控制日志是否开启
        - id: order_route
          uri: lb://service-order
          order: 1
          predicates:
            - Path=/order-serv/**
#            - Age= 18,60
          filters:
            - StripPrefix=1
#            - Log=true,true #控制日志是否开启

    nacos:
      discovery:
        server-addr:  localhost:8848