server:
   port: 8091
spring:
    application:
       name: service-order
    datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
       username: root
       password: 2333
    jpa:
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    cloud:
        nacos:
          discovery:
            server-addr: localhost:8848